{  "state":0,
   "products":[
         {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },

               {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },
                 {
            "id":"1U3OW86E6xBJWeFOn2EW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        },

        {
            "id":"1U3cW86e6xcJWeFsnqEW",
            "type":[{"id":1},{"name":"casual"}],
            "category":5,
            "typeClothing":2,

            "UsesColor":[

            ],
            "colorList":[
               "azul",
               "verde",
               "negro",
               "mostaza"
            ],
            "description":"vestido verano",
            "discount":10,
            "imageList":[
               "https://firebasestorage.googleapis.com/v0/b/bukuri-4ee3b.appspot.com/o/products%2Fimg-min.jpeg?alt\u003dmedia\u0026token\u003d128b7f45-e199-48ee-a557-61b70333c6d8"
            ],
            "size":[
               "medium",
               "small"
            ],
            "isCart":false,
            "isOutfit":false,
            "isWishList":false,
            "name":"Vestido",
            "priority":1,
            "promotion":true,
            "quantity":0,
            "retailPrice":55.0,
            "subNamePants":"none",
            "subNameShirt":"none",
            "wholesalePrice":30.0
        }
      ]
}